version: '3'

services:

    redis:
        image: redis
        expose:
            - "6379"
        networks:
            - app-network

    app:
        build: .
        image: kleberlyra/fullcycle-app
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s -template /opt/utils/env.tmpl:/var/www/.env /opt/utils/app-entrypoint.sh
        restart: always
        tty: true
        volumes:
            - ./app:/var/www
            - ./utils:/opt/utils:ro
        networks:
            - app-network
        depends_on: 
            - db
            - redis
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis

    nginx:
        build: .docker/nginx
        image: kleberlyra/fullcycle-nginx
        container_name: nginx
        entrypoint: dockerize -wait tcp://app:9000 -template /opt/utils/nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf /opt/utils/nginx-entrypoint.sh
        restart: always
        tty: true
        environment:
            - PHPFPM_HOST=app
            - PHPFPM_PORT=9000
        volumes:
            - ./app:/var/www
            - ./utils:/opt/utils:ro
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app
    
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dbstore:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
