version: '2.3'

services:

    redis:
        image: redis
        expose:
            - "6379"
        networks:
            - app-network
    app:
        #build: .
        image: kleberlyra/fullcycle-app
        container_name: app
        restart: always
        tty: true
        volumes:
            - aplication:/var/www
        networks:
            - app-network
        depends_on: 
            db:
                condition: service_healthy
            redis:
                condition: service_started

    nginx:
        #build: .docker/nginx
        image: kleberlyra/fullcycle-nginx
        container_name: nginx
        restart: always
        tty: true
        volumes_from:
            - app
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app
    
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        tty: true
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dbstore:/var/lib/mysql
        networks: 
            - app-network
        healthcheck:
            test: ["CMD-SHELL", 'mysql -u root -proot --database=laravel --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
            interval: 10s
            timeout: 10s
            retries: 4
volumes:
    aplication:

networks:
    app-network:
        driver: bridge